import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'theme.dart';
import 'services/app_state.dart';
import 'services/auth_service.dart';
import 'services/firebase_service.dart';
import 'screens/login_screen.dart';
import 'screens/home_screen.dart';
import 'screens/map_screen.dart';
import 'screens/requests_screen.dart';
import 'screens/volunteer_screen.dart';
import 'screens/report_screen.dart';
import 'screens/admin_shell.dart';
import 'models/models.dart';

// ── Generated by: flutterfire configure
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── Firebase initialization ────────────────────────────────────────
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.light,
    systemNavigationBarColor: Color(0xFF1A2E1A),
    systemNavigationBarIconBrightness: Brightness.light,
  ));

  runApp(
    ChangeNotifierProvider(
      create: (_) => AppState(),
      child: const FoodBridgeUserApp(),
    ),
  );
}

class FoodBridgeUserApp extends StatelessWidget {
  const FoodBridgeUserApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FoodBridge',
      theme: AppTheme.theme,
      debugShowCheckedModeBanner: false,
      home: const _AuthGate(),
    );
  }
}

// ─── Auth gate — listens to Firebase Auth state ───────────────────────────
class _AuthGate extends StatelessWidget {
  const _AuthGate();

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: AuthService().authStateChanges,
      builder: (context, snapshot) {
        // Still resolving
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            backgroundColor: AppColors.primary,
            body: Center(
              child: CircularProgressIndicator(color: Colors.white),
            ),
          );
        }

        final firebaseUser = snapshot.data;

        // Not logged in → show login
        if (firebaseUser == null) {
          return const LoginScreen();
        }

        // Logged in → hydrate AppUser from Firestore then show main shell
        return _HydrateUser(firebaseUser: firebaseUser);
      },
    );
  }
}

// ─── Hydrates AppUser from Firestore on first load ────────────────────────
class _HydrateUser extends StatefulWidget {
  final User firebaseUser;
  const _HydrateUser({required this.firebaseUser});

  @override
  State<_HydrateUser> createState() => _HydrateUserState();
}

class _HydrateUserState extends State<_HydrateUser> {
  @override
  void initState() {
    super.initState();
    _hydrate();
  }

  Future<void> _hydrate() async {
    final appState = context.read<AppState>();
    if (appState.isLoggedIn) return; // already set

    final user = await AuthService().fetchAppUser(widget.firebaseUser.uid);
    if (!mounted) return;

    if (user != null) {
      appState.setUser(user);
      FirebaseService().init(user.uid, user.name);
    } else {
      // Firestore profile missing — sign out and return to login
      await AuthService().signOut();
    }
  }

  @override
  Widget build(BuildContext context) {
    final appState = context.watch<AppState>();

    if (!appState.isLoggedIn) {
      return const Scaffold(
        backgroundColor: AppColors.primary,
        body: Center(child: CircularProgressIndicator(color: Colors.white)),
      );
    }

    if (appState.role == UserRole.admin) {
      return const AdminShell();
    }

    return MainShell(role: appState.role);
  }
}

// ─── Main shell — role-based bottom nav ───────────────────────────────────
class MainShell extends StatefulWidget {
  final UserRole role;
  const MainShell({super.key, required this.role});

  @override
  State<MainShell> createState() => _MainShellState();
}

class _MainShellState extends State<MainShell> {
  int _index = 0;

  // ── Nav configs per role ──────────────────────────────────────────
  List<_NavItem> get _items {
    if (widget.role == UserRole.volunteer) {
      return const [
        _NavItem(
            icon: Icons.task_outlined,
            activeIcon: Icons.task_rounded,
            label: 'Tasks'),
        _NavItem(
            icon: Icons.map_outlined,
            activeIcon: Icons.map_rounded,
            label: 'Map'),
        _NavItem(
            icon: Icons.task_alt_outlined,
            activeIcon: Icons.task_alt_rounded,
            label: 'Completed'),
        _NavItem(
            icon: Icons.flag_outlined,
            activeIcon: Icons.flag_rounded,
            label: 'Report',
            isAlert: true),
      ];
    }
    // User role
    return const [
      _NavItem(
          icon: Icons.home_outlined,
          activeIcon: Icons.home_rounded,
          label: 'Home'),
      _NavItem(
          icon: Icons.map_outlined,
          activeIcon: Icons.map_rounded,
          label: 'Map'),
      _NavItem(
          icon: Icons.inbox_outlined,
          activeIcon: Icons.inbox_rounded,
          label: 'Requests'),
      _NavItem(
          icon: Icons.directions_bike_outlined,
          activeIcon: Icons.directions_bike_rounded,
          label: 'Volunteer'),
      _NavItem(
          icon: Icons.flag_outlined,
          activeIcon: Icons.flag_rounded,
          label: 'Report',
          isAlert: true),
    ];
  }

  List<Widget> get _screens {
    if (widget.role == UserRole.volunteer) {
      return const [
        VolunteerScreen(),
        MapScreen(),
        VolunteerCompletedScreen(),
        ReportScreen(),
      ];
    }
    return const [
      HomeScreen(),
      MapScreen(),
      RequestsScreen(),
      VolunteerScreen(),
      ReportScreen(),
    ];
  }

  @override
  Widget build(BuildContext context) {
    // Clamp index when switching role (safety)
    final safeIndex = _index.clamp(0, _screens.length - 1);

    return Scaffold(
      body: IndexedStack(index: safeIndex, children: _screens),
      bottomNavigationBar: _buildNav(),
    );
  }

  Widget _buildNav() {
    final items = _items;
    return Container(
      decoration: const BoxDecoration(
        color: Color(0xFF1A2E1A),
        border: Border(top: BorderSide(color: Colors.white10, width: 0.5)),
      ),
      child: SafeArea(
        child: SizedBox(
          height: 62,
          child: Row(
            children: items.asMap().entries.map((e) {
              final i = e.key;
              final item = e.value;
              final active = i == _index;
              final alertColor = const Color(0xFFFF6B6B);

              Color activeColor;
              if (item.isAlert)
                activeColor = alertColor;
              else if (item.label == 'Volunteer' ||
                  item.label == 'Tasks' ||
                  item.label == 'Completed')
                activeColor = const Color(0xFF95D5B2);
              else
                activeColor = const Color(0xFF74C69D);

              return Expanded(
                child: GestureDetector(
                  onTap: () => setState(() => _index = i),
                  behavior: HitTestBehavior.opaque,
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      AnimatedContainer(
                        duration: const Duration(milliseconds: 200),
                        padding: const EdgeInsets.symmetric(
                            horizontal: 12, vertical: 4),
                        decoration: BoxDecoration(
                          color: active
                              ? activeColor.withOpacity(0.15)
                              : Colors.transparent,
                          borderRadius: BorderRadius.circular(20),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Icon(
                              active ? item.activeIcon : item.icon,
                              size: 22,
                              color: active
                                  ? activeColor
                                  : Colors.white.withOpacity(0.4),
                            ),
                            AnimatedSize(
                              duration: const Duration(milliseconds: 200),
                              child: active
                                  ? Padding(
                                      padding: const EdgeInsets.only(left: 6),
                                      child: Text(item.label,
                                          style: GoogleFonts.syne(
                                              fontSize: 11,
                                              fontWeight: FontWeight.w700,
                                              color: activeColor)),
                                    )
                                  : const SizedBox.shrink(),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 2),
                      if (!active)
                        Text(item.label,
                            style: GoogleFonts.syne(
                                fontSize: 9,
                                color: Colors.white.withOpacity(0.35))),
                    ],
                  ),
                ),
              );
            }).toList(),
          ),
        ),
      ),
    );
  }
}

class _NavItem {
  final IconData icon;
  final IconData activeIcon;
  final String label;
  final bool isAlert;
  const _NavItem({
    required this.icon,
    required this.activeIcon,
    required this.label,
    this.isAlert = false,
  });
}
