import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'admin_theme.dart';
import 'firebase_options.dart';      // generated by: flutterfire configure
import 'models/models.dart';
import 'services/app_state.dart';
import 'services/auth_service.dart';
import 'services/firebase_service.dart';
import 'screens/admin_login_screen.dart';
import 'screens/admin_dashboard_screen.dart';
import 'screens/admin_surplus_screen.dart';
import 'screens/admin_requests_screen.dart';
import 'screens/admin_waste_screen.dart';
import 'screens/admin_reports_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.light,
    systemNavigationBarColor: Color(0xFF1A2744),
    systemNavigationBarIconBrightness: Brightness.light,
  ));

  runApp(
    ChangeNotifierProvider(
      create: (_) => AppState(),
      child: const FoodBridgeAdminApp(),
    ),
  );
}

class FoodBridgeAdminApp extends StatelessWidget {
  const FoodBridgeAdminApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FoodBridge Admin',
      theme: AdminTheme.theme,
      debugShowCheckedModeBanner: false,
      home: const _AdminAuthGate(),
    );
  }
}

// ─── Auth gate ────────────────────────────────────────────────────────────
class _AdminAuthGate extends StatelessWidget {
  const _AdminAuthGate();

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: AuthService().authStateChanges,
      builder: (context, snap) {
        if (snap.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            backgroundColor: AdminColors.navy,
            body: Center(child: CircularProgressIndicator(color: Colors.white)),
          );
        }
        final fbUser = snap.data;
        if (fbUser == null) return const AdminLoginScreen();
        return _HydrateAdmin(uid: fbUser.uid);
      },
    );
  }
}

// ─── Hydrate admin user from Firestore ───────────────────────────────────
class _HydrateAdmin extends StatefulWidget {
  final String uid;
  const _HydrateAdmin({required this.uid});
  @override
  State<_HydrateAdmin> createState() => _HydrateAdminState();
}

class _HydrateAdminState extends State<_HydrateAdmin> {
  @override
  void initState() { super.initState(); _load(); }

  Future<void> _load() async {
    final appState = context.read<AppState>();
    if (appState.isLoggedIn) return;

    final user = await AuthService().fetchAppUser(widget.uid);
    if (!mounted) return;

    if (user == null || user.role != UserRole.admin) {
      // Not admin — sign out
      await AuthService().signOut();
      return;
    }

    appState.setUser(user);
    FirebaseService().init(user.uid, user.name);
  }

  @override
  Widget build(BuildContext context) {
    final appState = context.watch<AppState>();
    if (!appState.isLoggedIn) {
      return const Scaffold(
        backgroundColor: AdminColors.navy,
        body: Center(child: CircularProgressIndicator(color: Colors.white)),
      );
    }
    return const AdminShell();
  }
}

// ─── Admin shell: 4-tab bottom nav ───────────────────────────────────────
class AdminShell extends StatefulWidget {
  const AdminShell({super.key});
  @override
  State<AdminShell> createState() => _AdminShellState();
}

class _AdminShellState extends State<AdminShell> {
  int _index = 0;

  static const _screens = [
    AdminDashboardScreen(),
    AdminSurplusScreen(),
    AdminRequestsScreen(),
    AdminWasteScreen(),
    AdminReportsScreen(),
  ];

  static const _items = [
    _NavItem(icon: Icons.dashboard_outlined,   active: Icons.dashboard,      label: 'Dashboard'),
    _NavItem(icon: Icons.inventory_2_outlined, active: Icons.inventory_2,    label: 'Surplus'),
    _NavItem(icon: Icons.pending_outlined,     active: Icons.pending,        label: 'Requests'),
    _NavItem(icon: Icons.recycling_outlined,   active: Icons.recycling,      label: 'Waste'),
    _NavItem(icon: Icons.flag_outlined,        active: Icons.flag,           label: 'Reports',
        isAlert: true),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: IndexedStack(index: _index, children: _screens),
      bottomNavigationBar: _buildNav(),
    );
  }

  Widget _buildNav() {
    return Container(
      decoration: const BoxDecoration(
        color: AdminColors.navy,
        border: Border(top: BorderSide(color: Colors.white10, width: 0.5)),
      ),
      child: SafeArea(
        child: SizedBox(
          height: 62,
          child: Row(
            children: _items.asMap().entries.map((e) {
              final i    = e.key;
              final item = e.value;
              final active = i == _index;
              final color  = item.isAlert
                  ? const Color(0xFFFF6B6B)
                  : const Color(0xFF74C69D);

              return Expanded(
                child: GestureDetector(
                  onTap: () => setState(() => _index = i),
                  behavior: HitTestBehavior.opaque,
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      AnimatedContainer(
                        duration: const Duration(milliseconds: 200),
                        padding: const EdgeInsets.symmetric(
                            horizontal: 12, vertical: 4),
                        decoration: BoxDecoration(
                          color: active
                              ? color.withOpacity(0.15)
                              : Colors.transparent,
                          borderRadius: BorderRadius.circular(20),
                        ),
                        child: Row(mainAxisSize: MainAxisSize.min, children: [
                          Icon(active ? item.active : item.icon,
                              size: 22,
                              color: active
                                  ? color
                                  : Colors.white.withOpacity(0.4)),
                          AnimatedSize(
                            duration: const Duration(milliseconds: 200),
                            child: active
                                ? Padding(
                                    padding: const EdgeInsets.only(left: 6),
                                    child: Text(item.label,
                                        style: GoogleFonts.syne(
                                            fontSize: 11,
                                            fontWeight: FontWeight.w700,
                                            color: color)),
                                  )
                                : const SizedBox.shrink(),
                          ),
                        ]),
                      ),
                      const SizedBox(height: 2),
                      if (!active)
                        Text(item.label, style: GoogleFonts.syne(
                            fontSize: 9,
                            color: Colors.white.withOpacity(0.35))),
                    ],
                  ),
                ),
              );
            }).toList(),
          ),
        ),
      ),
    );
  }
}

class _NavItem {
  final IconData icon;
  final IconData active;
  final String label;
  final bool isAlert;
  const _NavItem({required this.icon, required this.active,
      required this.label, this.isAlert = false});
}
