// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyppF1F5EMyvuyXGbDTdJwwJ42xM8TIKs',
    appId: '1:249295351708:web:73bf8e04542a19a31a2259',
    messagingSenderId: '249295351708',
    projectId: 'foodbridge-rohan-9cb08',
    authDomain: 'foodbridge-rohan-9cb08.firebaseapp.com',
    databaseURL: 'https://foodbridge-rohan-9cb08-default-rtdb.firebaseio.com',
    storageBucket: 'foodbridge-rohan-9cb08.firebasestorage.app',
    measurementId: 'G-QXTHP9XT4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAzzSAVniI1BeL1JJ-dbUbdwtfHTheLzs',
    appId: '1:249295351708:android:ef8452cb09bdd7571a2259',
    messagingSenderId: '249295351708',
    projectId: 'foodbridge-rohan-9cb08',
    databaseURL: 'https://foodbridge-rohan-9cb08-default-rtdb.firebaseio.com',
    storageBucket: 'foodbridge-rohan-9cb08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCefc5aqjOIhF4eGnn9f2VDq0yxuhK50g',
    appId: '1:249295351708:ios:d763ced67290220f1a2259',
    messagingSenderId: '249295351708',
    projectId: 'foodbridge-rohan-9cb08',
    storageBucket: 'foodbridge-rohan-9cb08.firebasestorage.app',
    iosBundleId: 'com.example.foodbridgeUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCefc5aqjOIhF4eGnn9f2VDq0yxuhK50g',
    appId: '1:249295351708:ios:d763ced67290220f1a2259',
    messagingSenderId: '249295351708',
    projectId: 'foodbridge-rohan-9cb08',
    storageBucket: 'foodbridge-rohan-9cb08.firebasestorage.app',
    iosBundleId: 'com.example.foodbridgeUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyppF1F5EMyvuyXGbDTdJwwJ42xM8TIKs',
    appId: '1:249295351708:web:7674608b5c5df6231a2259',
    messagingSenderId: '249295351708',
    projectId: 'foodbridge-rohan-9cb08',
    authDomain: 'foodbridge-rohan-9cb08.firebaseapp.com',
    storageBucket: 'foodbridge-rohan-9cb08.firebasestorage.app',
    measurementId: 'G-PG1Z30VR5G',
  );

}